name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We have to use the Release mode, otherwise it would take forever.
      - name: Test
        run: cargo test --release

      - name: Test usvgr
        working-directory: usvgr
        run: cargo test

      - name: Build svgr without default support
        run: cargo check --no-default-features

      - name: Build usvgr without default support
        working-directory: usvgr
        run: cargo check --no-default-features

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.51.0

      - name: Build
        run: cargo build --features dump-svg
